export enum Types {
  fairy = 'fairy',
  ice = 'ice',
  grass = 'grass',
  steel = 'steel',
  rock = 'rock',
  dark = 'dark',
  psychic = 'psychic',
  water = 'water',
  ghost = 'ghost',
  ground = 'ground',
  dragon = 'dragon',
  electric = 'electric',
  fire = 'fire',
  bug = 'bug',
  poison = 'poison',
  flying = 'flying',
  fighting = 'fighting',
  normal = 'normal',
}
